FROM node:16.13.2

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY services/todo services/todo
COPY services/shared services/shared

WORKDIR /usr/src/app/services/todo

EXPOSE 8080

CMD ["yarn","start:todo"]