receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://localhost:5173
          allowed_headers: ["Content-Type", "Authorization"]

exporters:
  otlp:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
